const KEYS={estoque:'estoque_validade_db',catalogo:'catalogo_produtos_db',fiados:'vendas_fiadas_db',backup:'backup_aviso_db'};
let estoque=ler(KEYS.estoque,[]), catalogo=ler(KEYS.catalogo,{}), fiados=ler(KEYS.fiados,[]), html5QrCode=null;

function ler(chave, padrao){try{return JSON.parse(localStorage.getItem(chave)||JSON.stringify(padrao))}catch{return padrao}}
function salvar(){localStorage.setItem(KEYS.estoque,JSON.stringify(estoque));localStorage.setItem(KEYS.catalogo,JSON.stringify(catalogo));localStorage.setItem(KEYS.fiados,JSON.stringify(fiados));atualizarStatus()}
function escapar(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function dataBR(v){return v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'--'}
function hojeISO(){return new Date().toISOString().slice(0,10)}

window.onload=()=>{renderEstoque();renderFiados();configurarLeitorUSB();mostrarAvisoBackup();atualizarStatus()};
function configurarLeitorUSB(){document.querySelector('#nomeProduto').addEventListener('keypress',e=>{if(e.key==='Enter'){e.preventDefault();buscarProdutoPorCodigo(e.target.value.trim())}})}
function iniciarCamara(){const r=document.querySelector('#reader');r.hidden=false;html5QrCode=new Html5Qrcode('reader');html5QrCode.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:150}},texto=>{pararCamara();document.querySelector('#nomeProduto').value=texto;buscarProdutoPorCodigo(texto)},()=>{}).catch(()=>{alert('Não foi possível abrir a câmera. Confira a permissão do celular.');r.hidden=true})}
function pararCamara(){if(html5QrCode){html5QrCode.stop().then(()=>document.querySelector('#reader').hidden=true).catch(()=>{})}}
function buscarProdutoPorCodigo(codigo){if(!codigo)return;if(/^\d+$/.test(codigo)){const conhecido=catalogo[codigo];if(conhecido){document.querySelector('#nomeProduto').value=conhecido;mostrarProduto(`Produto encontrado: ${conhecido}`);return}document.querySelector('#nomeProduto').value='';document.querySelector('#nomeProduto').placeholder=`Produto novo (${codigo}). Digite o nome`;document.querySelector('#nomeProduto').dataset.codigo=codigo;mostrarProduto('Produto novo. Digite o nome e salve para guardar este código.')} }
function mostrarProduto(texto){const el=document.querySelector('#mensagemProduto');el.textContent=texto;el.hidden=false}
function cadastrarProduto(){const campo=document.querySelector('#nomeProduto'),nome=campo.value.trim(),qtd=Number(document.querySelector('#qtdProduto').value),dataValidade=document.querySelector('#dataVencimento').value,codigo=campo.dataset.codigo||(/^[0-9]+$/.test(nome)?nome:'');if(!nome||!qtd||!dataValidade){alert('Informe o nome, a quantidade e a data de vencimento.');return}if(codigo){catalogo[codigo]=nome}estoque.push({id:Date.now(),codigo,nome,qtd,dataValidade});salvar();campo.value='';campo.dataset.codigo='';campo.placeholder='Digite ou escaneie o código';document.querySelector('#qtdProduto').value='1';document.querySelector('#dataVencimento').value='';document.querySelector('#mensagemProduto').hidden=true;renderEstoque();alert('Produto salvo com sucesso.')}
function obterStatusValidade(data){const hoje=new Date();hoje.setHours(0,0,0,0);const venc=new Date(data+'T00:00:00'),dias=Math.ceil((venc-hoje)/86400000);if(dias<=3)return{classe:'status-alerta',texto:dias<0?'VENCIDO!':`Vence em ${dias} dia(s)!`};if(dias<=7)return{classe:'status-atencao',texto:`Vence em ${dias} dias`};return{classe:'status-ok',texto:`Vence em ${dias} dias`}}
function renderEstoque(){const c=document.querySelector('#listaEstoque');if(!estoque.length){c.innerHTML='<p class="muted">Nenhum produto cadastrado no estoque.</p>';return}estoque.sort((a,b)=>a.dataValidade.localeCompare(b.dataValidade));c.innerHTML=estoque.map(p=>{const s=obterStatusValidade(p.dataValidade);return `<div class="item-estoque ${s.classe}"><div><b>${escapar(p.qtd)}x ${escapar(p.nome)}</b><br><small>Vencimento: ${dataBR(p.dataValidade)} — <b>${s.texto}</b></small></div><button class="btn-remover" onclick="removerProduto(${p.id})">Apagar</button></div>`}).join('')}
function removerProduto(id){if(!confirm('Tem certeza que deseja apagar este produto?'))return;estoque=estoque.filter(p=>p.id!==id);salvar();renderEstoque()}

function cadastrarFiado(){const nome=document.querySelector('#clienteNome').value.trim(),telefone=document.querySelector('#clienteTelefone').value.trim(),itens=document.querySelector('#fiadoItens').value.trim(),total=numero(document.querySelector('#fiadoTotal').value),vencimento=document.querySelector('#fiadoVencimento').value;if(!nome||!itens||!total||!vencimento){alert('Informe o nome, os produtos, o valor total e a data de pagamento.');return}fiados.push({id:Date.now(),cliente:nome,telefone,itens,total,pago:0,dataCompra:hojeISO(),vencimento,status:'pendente'});salvar();['clienteNome','clienteTelefone','fiadoItens','fiadoTotal','fiadoVencimento'].forEach(id=>document.querySelector('#'+id).value='');renderFiados();alert('Venda fiada guardada.')}
function numero(v){return Number(String(v).replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0}
function mostrarContas(filtro){renderFiados(filtro)}
function renderFiados(filtro='todas'){const c=document.querySelector('#listaFiados'),lista=fiados.filter(f=>filtro==='pendentes'?f.pago<f.total:true);if(!lista.length){c.innerHTML='<p class="muted">Nenhuma conta encontrada.</p>';return}c.innerHTML=lista.slice().sort((a,b)=>a.vencimento.localeCompare(b.vencimento)).map(f=>{const falta=Math.max(0,f.total-f.pago),atrasada=falta>0&&f.vencimento<hojeISO();return `<div class="item-fiado ${atrasada?'status-alerta':''}"><div><b>${escapar(f.cliente)}</b><br><small>${escapar(f.itens).replace(/\n/g,'<br>')}<br>Total: <b>${moeda(f.total)}</b> | Pago: ${moeda(f.pago)} | Falta: <b>${moeda(falta)}</b><br>Pagamento: ${dataBR(f.vencimento)} ${falta?'':'— PAGO'}</small></div><div class="item-actions">${falta?`<button class="btn-pago" onclick="marcarPago(${f.id})">Marcar como pago</button>`:''}<button class="btn-msg" onclick="prepararRecibo(${f.id})">Enviar recibo</button><button class="btn-imprimir" onclick="imprimirRecibo(${f.id})">Imprimir</button><button class="btn-remover" onclick="removerFiado(${f.id})">Apagar</button></div></div>`}).join('')}
function marcarPago(id){const f=fiados.find(x=>x.id===id);if(!f)return;const valor=prompt(`Quanto foi pago?\nFalta ${moeda(f.total-f.pago)}`,String(f.total-f.pago).replace('.',','));if(valor===null)return;f.pago=Math.min(f.total,f.pago+numero(valor));salvar();renderFiados();if(f.pago>=f.total&&confirm('Conta quitada. Deseja preparar uma mensagem de agradecimento?'))abrirWhatsApp(`Olá, ${f.cliente}! Confirmamos o recebimento do pagamento. Muito obrigado por ser nosso cliente!`)}
function removerFiado(id){if(!confirm('Tem certeza que deseja apagar esta venda?'))return;fiados=fiados.filter(f=>f.id!==id);salvar();renderFiados()}
function mensagemFiado(f){const falta=Math.max(0,f.total-f.pago),dias=Math.ceil((new Date(f.vencimento+'T00:00:00')-new Date(new Date().toDateString()))/86400000);let prazo=dias>0?`Faltam ${dias} dias para o vencimento`:dias===0?'Sua conta vence hoje':`Sua conta está vencida há ${Math.abs(dias)} dia(s)`;return `Olá, ${f.cliente}!\n\n${prazo} referente à sua compra de ${moeda(f.total)}.\nValor que falta pagar: ${moeda(falta)}.\nData combinada: ${dataBR(f.vencimento)}.\n\nSe já realizou o pagamento, por favor, desconsidere.\nObrigado por ser nosso cliente!`}
function recibo(f){return `RECIBO DE COMPRA\n\nCliente: ${f.cliente}\nData da compra: ${dataBR(f.dataCompra)}\nPagamento combinado: ${dataBR(f.vencimento)}\n\nProdutos:\n${f.itens}\n\nTotal: ${moeda(f.total)}\nPago: ${moeda(f.pago)}\nFalta pagar: ${moeda(Math.max(0,f.total-f.pago))}\n\nObrigado por ser nosso cliente!`}
function prepararRecibo(id){const f=fiados.find(x=>x.id===id);if(!f)return;const texto=recibo(f);if(confirm('OK para enviar o recibo da compra.\n\n'+texto))abrirWhatsApp(texto)}
function gerarRelatorioFiados(){const lista=fiados.filter(f=>f.pago<f.total);if(!lista.length){alert('Não há contas pendentes.');return}const texto='CONTAS PENDENTES\n\n'+lista.map(f=>`${f.cliente} — falta ${moeda(f.total-f.pago)} — pagamento: ${dataBR(f.vencimento)}`).join('\n');if(confirm(texto+'\n\nDeseja abrir o WhatsApp?'))abrirWhatsApp(texto)}
function abrirWhatsApp(texto){window.open('https://api.whatsapp.com/send?text='+encodeURIComponent(texto),'_blank')}
function mostrarHistorico(){const termo=document.querySelector('#buscaCliente').value.trim().toLowerCase(),c=document.querySelector('#historicoCliente');if(!termo){c.innerHTML='<p class="muted">Digite o nome do cliente.</p>';return}const lista=fiados.filter(f=>f.cliente.toLowerCase().includes(termo));if(!lista.length){c.innerHTML='<p class="muted">Nenhuma compra encontrada.</p>';return}const total=lista.reduce((s,f)=>s+f.total,0);c.innerHTML=`<p><b>${lista.length} compra(s)</b> — Total consumido: <b>${moeda(total)}</b></p>`+lista.map(f=>`<div class="item-fiado"><div>${dataBR(f.dataCompra)} — ${escapar(f.itens).replace(/\n/g,'<br>')}<br>Total: ${moeda(f.total)} — ${f.pago>=f.total?'Pago':'Em aberto'}</div><button class="btn-imprimir" onclick="imprimirRecibo(${f.id})">Imprimir</button></div>`).join('')}
function gerarRelatorio(dias){const lista=estoque.filter(p=>{const d=Math.ceil((new Date(p.dataValidade+'T00:00:00')-new Date(new Date().toDateString()))/86400000);return d<=dias});if(!lista.length){alert(`Nenhum produto vencendo nos próximos ${dias} dias.`);return}const texto=`RELATÓRIO DE VENCIMENTOS (${dias} DIAS)\n\n`+lista.map(p=>`${p.qtd}x ${p.nome} — ${dataBR(p.dataValidade)}`).join('\n');if(confirm(texto+'\n\nDeseja abrir o WhatsApp?'))abrirWhatsApp(texto)}
function imprimirRelatorioEstoque(){imprimirPagina('Lista de produtos\n\n'+estoque.map(p=>`${p.qtd}x ${p.nome} — vence em ${dataBR(p.dataValidade)}`).join('\n'))}
function imprimirRecibo(id){const f=fiados.find(x=>x.id===id);if(f)imprimirPagina(recibo(f))}
function imprimirPagina(texto){const w=window.open('','_blank');w.document.write(`<pre style="font:16px Arial;white-space:pre-wrap;padding:20px">${escapar(texto)}</pre><script>window.print()<\\/script>`);w.document.close()}

function dadosBackup(){return{versao:1,data: new Date().toISOString(),estoque,catalogo,fiados}}
function fazerBackup(){const blob=new Blob([JSON.stringify(dadosBackup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`copia-de-seguranca-${hojeISO()}.json`;a.click();localStorage.setItem(KEYS.backup,new Date().toISOString());atualizarStatus();alert('Cópia de segurança criada. Guarde o arquivo em local seguro.')}
function restaurarBackup(){document.querySelector('#arquivoBackup').click()}
document.querySelector('#arquivoBackup')?.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const b=JSON.parse(reader.result);if(!b.estoque||!b.catalogo||!b.fiados)throw Error();if(!confirm('Usar esta cópia? Os dados atuais serão substituídos.'))return;estoque=b.estoque;catalogo=b.catalogo;fiados=b.fiados;salvar();renderEstoque();renderFiados();alert('Cópia restaurada com sucesso.')}catch{alert('Este arquivo não é uma cópia válida.')}};reader.readAsText(file)})
function mostrarAvisoBackup(){if(!localStorage.getItem(KEYS.backup)){const e=document.querySelector('#avisoBackup');e.hidden=false;e.innerHTML='<b>Antes de começar:</b> seus dados estão somente neste aparelho. Faça uma <b>cópia de segurança</b> para evitar a perda das informações. <button class="btn-light" onclick="fazerBackup()">Guardar cópia</button>'}}
function atualizarStatus(){const s=document.querySelector('#statusApp');if(!s)return;s.textContent=localStorage.getItem(KEYS.backup)?'Cópia de segurança guardada neste aparelho.':'Cópia de segurança ainda não criada.'}
